replicaCount: 1
image:
  repository: ghcr.io/zoonderkins/hugo-k8s-dashboard
  tag: 740650a0ab98f5cb1f0b3e2eba928539c56153ce
  pullPolicy: Always
  # Pull secrets for private image registry
  pullSecrets:
    - name: regcred

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false