replicaCount: 1
image:
  repository: ghcr.io/zoonderkins/hugo-k8s-dashboard
  tag: 1aa336c946749cc98fb59d3f8117d934fe2055ea
  pullPolicy: Always
  # Pull secrets for private image registry
  pullSecrets:
    - name: regcred

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false