replicaCount: 1
image:
  repository: ghcr.io/zoonderkins/hugo-k8s-dashboard
  tag: 69f3655f2202a3f3b6c1426e2421683a93728402
  pullPolicy: Always
  # Pull secrets for private image registry
  pullSecrets:
    - name: regcred

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false