replicaCount: 1
image:
  repository: ghcr.io/zoonderkins/hugo-k8s-dashboard
  tag: 70035819cfe4d4a900e1543b1fb27dae27eb9cdc
  pullPolicy: Always
  # Pull secrets for private image registry
  pullSecrets:
    - name: regcred

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false