replicaCount: 1
image:
  repository: ghcr.io/zoonderkins/hugo-k8s-dashboard
  tag: 3f97b3ab2eab1dc7c174bcb2ce524b8f633e1cfc
  pullPolicy: Always
  # Pull secrets for private image registry
  pullSecrets:
    - name: regcred

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false