apiVersion: apps/v1
kind: Deployment
metadata:
  name: hugo-site
  labels:
    app: hugo-site
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hugo-site
  template:
    metadata:
      labels:
        app: hugo-site
      annotations:
        # This forces a restart when new content is committed
        checksum/content: {{ now | quote }}
        # Add image tag as annotation to force restart when tag changes
        image-tag: "{{ .Values.image.tag }}"
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: hugo-k8s-dashboard
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
