apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-push
  namespace: prod
---
# Cluster role for listing pods across all namespaces
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-lister
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
# Cluster role binding to allow the service account to list pods across the cluster
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-push-cluster-pod-lister
subjects:
- kind: ServiceAccount
  name: github-push
  namespace: prod
roleRef:
  kind: ClusterRole
  name: pod-lister
  apiGroup: rbac.authorization.k8s.io
---
# Role for namespace-specific resources
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-push-role
  namespace: prod
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
---
# Role binding for namespace resources
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-push-rolebinding
  namespace: prod
subjects:
- kind: ServiceAccount
  name: github-push
  namespace: prod
roleRef:
  kind: Role
  name: github-push-role
  apiGroup: rbac.authorization.k8s.io
