name: Build and Push Hugo Static Site

on:
  push:
    branches: [master]
    paths:
      - 'charts/**'
  workflow_dispatch:

# Add a conditional check for commit messages containing [ci]
jobs:
  check-commit:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Check commit message or path changes
        id: check
        run: |
          if git log -1 --pretty=format:%s | grep -q "\[ci\]"; then
            echo "Commit message contains [ci], triggering workflow"
            echo "should_run=true" >> $GITHUB_OUTPUT
          elif git diff --name-only HEAD^ HEAD | grep -q "^charts/"; then
            echo "Changes detected in charts directory, triggering workflow"
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "No [ci] in commit message and no changes in charts directory"
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi

  hugo-deploy:
    needs: check-commit
    if: ${{ needs.check-commit.outputs.should_run == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.147.5'
          extended: true

      - name: Build Hugo Site
        run: hugo --minify

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag from values.yaml
        id: extract-tag
        run: |
          TAG=$(grep -E '^\s*tag:' charts/hugo-site/values.yaml | sed -E 's/^\s*tag:\s*([^\s]+).*/\1/')
          echo "Using tag from values.yaml: $TAG"
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
          if [ -z "$TAG" ]; then
            echo "No tag found in values.yaml, defaulting to commit SHA"
            echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
          fi

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v4

env:
  IMAGE_NAME: hugo-k8s-dashboard

